# Generated by Django 3.2.7 on 2021-11-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middleName', models.CharField(max_length=50, verbose_name='Отчество')),
                ('fullname', models.CharField(max_length=50, verbose_name='Полное имя')),
                ('structuralDivision', models.CharField(max_length=50, verbose_name='Структурное подразделение')),
                ('department', models.CharField(max_length=50, verbose_name='Отдел')),
                ('heldPost', models.CharField(max_length=50, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
